name: Tests

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Running the tests
        run: npm lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Running the tests
        run: npm test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Install WordPress
        run: |
          npm run wp-env start

      - name: Running the tests
        run: |
          npm run test:e2e
