name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Running the tests
        run: npm run lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Running the tests
        run: npm run test:unit

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Npm install and build
        run: |
          npm ci
          npm run build

      - name: Install WordPress
        run: |
          npm run wp-env start

      - name: Running the tests
        run: |
          npm run test:e2e

  deploy:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    needs: [test, unit-tests, e2e-tests]
    steps:

      - uses: actions/checkout@v2

      - name: Build
        if: contains(github.ref, 'tags/')
        run: |
          npm ci
          npm run build

      - name: WordPress Plugin Deploy
        if: contains(github.ref, 'tags/')
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: flexible-table-block
